### ISSUE TITLE
Fail to launch rerank model by using cmdline

### ISSUE THREAD

**Issue by harryzwh** [xorbitsai/inference#2914]
### System Info / 系統信息

docker image with version of v1.3.0.post1

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [x] docker / docker
- [ ] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

v1.3.0.post1

### The command used to start Xinference / 用以启动 xinference 的命令

xinference-local -H 0.0.0.0

### Reproduction / 复现过程

Try to launch bge-reranker-v2-m3 model. In web GUI, the model can be launched with defalut setting. However, when using cmdline to execute 
`xinference launch --model-name bge-reranker-v2-m3 --model-type rerank --replica 1 --n-gpu auto`
which is copied from the web GUI. It fails to launch and outputs the error as follow:

root@ba99551c03cf:/opt/inference# xinference launch --model-name bge-reranker-v2-m3 --model-type rerank --replica 1 --n-gpu auto
Launch model name: bge-reranker-v2-m3 with kwargs: {}
Traceback (most recent call last):
  File "/usr/local/bin/xinference", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/xinference/deploy/cmdline.py", line 935, in model_launch
    model_uid = client.launch_model(
  File "/usr/local/lib/python3.10/dist-packages/xinference/client/restful/restful_client.py", line 1007, in launch_model
    raise RuntimeError(
RuntimeError: Failed to launch model, detail: [address=0.0.0.0:39441, pid=4557] CrossEncoder.__init__() got an unexpected keyword argument 'reasoning_content'

it seems that the keyword argument 'reasoning_content' that added for the LLM model is accidentally passed to rerank model when using cmdline.

### Expected behavior / 期待表现

Using cmdline
`xinference launch --model-name bge-reranker-v2-m3 --model-type rerank --replica 1 --n-gpu auto`
can also launch the rerank model.

**Comment by qinxuye** [comment]
It should be introduced by #2905 , @amumu96 could you help to address this issue?
