### PR TITLE
BLD: require peft>=0.18.0 for transformers 5.x compatibility

### PR DESCRIPTION
**Pull request by OliverBryant**
## Problem

Launching any rerank model on the `sentence_transformers` engine fails at load time with:

```
ImportError: Failed to import module 'sentence-transformers': cannot import name
'HybridCache' from 'transformers' (.../transformers/__init__.py)

Please make sure 'sentence-transformers' is installed. You can install it by
`pip install sentence-transformers`
```

The suggested remedy is misleading — `sentence-transformers` is installed and is not the problem.

## Root cause

`peft<=0.17.1` imports `HybridCache` at **module level** in `peft/peft_model.py`:

```python
from transformers import Cache, DynamicCache, EncoderDecoderCache, HybridCache, PreTrainedModel
```

`HybridCache` was removed in **transformers 5.0.0** (present in 4.57.1, gone from 5.0.0 onward). Because `peft` declares an *unbounded* `transformers` requirement, pip resolves the incompatible pair without any warning, so images build fine and the failure only appears at runtime.

The failing import chain:

```
xinference/model/rerank/sentence_transformers/core.py  ->  import sentence_transformers
  -> sentence_transformers/base/model_card.py          ->  from transformers import TrainerCallback
  -> transformers/trainer_utils.py                     ->  from peft import PeftMixedModel, PeftModel
  -> peft/peft_model.py                                ->  ImportError: cannot import name 'HybridCache'
```

`core.py` catches the `ImportError` and re-raises it as "Failed to import module 'sentence-transformers'", which hides the real cause. GGUF LLMs never touch this chain, so on an affected image LLMs work while rerank/embedding models appear broken — which makes this easy to misdiagnose as a rerank bug.

The `<=0.17.1` upper bound was introduced in #4249 while transformers was still 4.x. It became self-inconsistent once `xinference/deploy/docker/requirements-runtime.txt` moved to `transformers==5.13.1`: the GPU image installs xinference under that constraint, and the CPU image pins both in `requirements_cpu-ml.txt` (`transformers>=4.53.3` + `peft<=0.17.1`).

`peft` **0.18.0** moved the `HybridCache` import inside the function that needs it, so it no longer breaks at import time.

## Fix

Require `peft>=0.18.0` in the three places the pin appears:

- `pyproject.toml` — also covers the GPU image, which installs xinference with `--constraint requirements-runtime.txt`
- `xinference/deploy/docker/requirements_cpu/requirements_cpu-ml.txt`
- `.github/workflows/python.yaml`

Comments were added at the first two sites recording the transformers-5.x constraint, so the bound is not lowered again without checking the shipped transformers major version.

## Verification

In a clean venv:

- `transformers==5.13.1` + `peft==0.17.1` installs with no pip warning and reproduces the exact `ImportError` from the report.
- With `peft>=0.18.0` (resolved 0.20.0) against the same `transformers==5.13.1`: `import sentence_transformers`, `from sentence_transformers.cross_encoder import CrossEncoder`, a full `CrossEncoder.predict` rerank call, and `from peft import PeftModel, PeftMixedModel` (used by `llm/transformers/core.py`) all succeed.
- `pre-commit run --files <changed files>` passes; `pyproject.toml` parses and resolves to `peft>=0.18.0`.

Not run locally: rerank tests that require model downloads or GPU, and a full image rebuild — both too costly in this environment. `test_auto_detect_type` fails on my machine both with and without this change, due to a pre-existing local numpy/scipy ABI mismatch unrelated to the patch.

### CODE REVIEW

File: pyproject.toml [hunk 1]
```diff
@@ -57,7 +57,11 @@ dependencies = [
     "nvidia-ml-py",
     "pynvml>=12",
     "async-timeout",
-    "peft<=0.17.1",
+    # peft 0.17.1 and below import HybridCache at module level, which was
+    # removed in transformers 5.0.0. peft declares an unbounded transformers
+    # requirement, so pinning it low silently breaks any transformers 5.x
+    # install (see the sentence-transformers rerank import chain).
+    "peft>=0.18.0",
```
[the remark this answers is not in the document]
Comment (OliverBryant) [reply pyproject.toml:64]: Thanks for the review, but this one is a false positive — the change to `.github/workflows/python.yaml` **is** included in this PR.

It is the first file in the diff:

```diff
@@ -455,7 +455,7 @@ jobs:
           pip install -U "FlagEmbedding==1.3.5"
-          pip install -U "peft<=0.17.1"
+          pip install -U "peft>=0.18.0"
```

`GET /repos/xorbitsai/inference/pulls/5260/files` returns all three paths:

- `.github/workflows/python.yaml`
- `pyproject.toml`
- `xinference/deploy/docker/requirements_cpu/requirements_cpu-ml.txt`

`grep -n peft .github/workflows/python.yaml` on the branch head reports a single occurrence, line 458: `pip install -U "peft>=0.18.0"`. So all three pins are already consistent and no further change is needed.

**Review by qinxuye — APPROVED** [review]
LGTM
